# Generated by Django 6.0.1 on 2026-03-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='location',
            field=models.CharField(default='City Hospital', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='services',
            field=models.CharField(default='General Consultation', max_length=200),
        ),
    ]
