# Generated by Django 6.0.1 on 2026-03-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_search', '0002_doctor_location_doctor_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(default='No information provided.'),
        ),
    ]
